name: Build Workflow

run-name: 'Build Workflow -- ${{ github.head_ref || github.ref_name }}'

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  BRANCH_NAME: ${{github.ref_name}}

jobs:
  build-job:
    name: Build Job
    runs-on: self-hosted
    if: github.repository_owner == 'ikmdev'
    steps:
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      
      - name: Build IKMDEV Code
        uses: ikmdev/maven-clean-install-build-action@main
        with:
          branch_name: ${{env.BRANCH_NAME}}